#!/bin/bash
#SBATCH --account=guellili-slr-automation
#SBATCH --qos=bbdefault
#SBATCH --time=3:0:0
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16G
#SBATCH --job-name=own_s5_franzosa
#SBATCH --output=/rds/projects/g/guellili-slr-automation/mehvish/thesis/results/own_s5_franzosa_%j.out

module purge
module load bear-apps/2021a/live
module load Python/3.9.5-GCCcore-10.3.0
source /rds/projects/g/guellili-slr-automation/mehvish/thesis/rf_boruta_env/bin/activate
python /rds/projects/g/guellili-slr-automation/mehvish/thesis/results/own_method_style5_franzosa.py